### ISSUE TITLE
Unknown Helicopter 2

### ISSUE THREAD

**Issue by gbinal** [gbinal/dc-helicopters#17]
_In January 2019, I noticed what looks like (or reminds me of) a MD500 flying in circles around the Nationals ballpark. I don’t believe it is military but am not sure. If you’ve got any ideas, let me know and I’ll update the site._

![picture I took of it](https://helicoptersofdc.com/pictures/unknown-helicopter-2-1.jpg)
![picture I took of it](https://helicoptersofdc.com/pictures/unknown-helicopter-2-2.jpg)
![picture I took of it](https://helicoptersofdc.com/pictures/unknown-helicopter-2-3.jpg)

**Comment by gbinal** [comment]
...

**Comment by gbinal** [comment]
Some suspects: 
* http://www.heloflights.com/

**Comment by jadams** [comment]
The only MD500 I know of in the DC area is:
[N9233F](https://registry.faa.gov/aircraftinquiry/NNum_Results.aspx?NNumbertxt=9233F)
Owned by [Bussman Aviation](https://www.heloflights.com)

**Comment by USAF2024** [comment]
That is the Prince George's County, MD Police. It's the MD 520N. They have 4 of them

**Comment by shaunindc** [comment]
That’s definitely the Bussmann Aviation MD 500C (N9233F[N9233F](https://www.heloflights.com/Gallery/PictureViewer.asp?filename=ScrapBook/Image04.jpg) ).
