### ISSUE TITLE
Try other flight apps to see if better for helicopter spotting

### ISSUE THREAD

**Issue by gbinal** [gbinal/dc-helicopters#31]
* [x] flightstats
* [X] flight tracker free
* [X] flightview

**Comment by wiseman** [comment]
Have you tried https://adsbexchange.com/ ?  The coverage isn't as good as FR24, is probably better than opensky, but doesn't censor any aircraft--which means that often it's the best way to track the more interesting ones.

They have a new interface in beta that lets you link directly to an aircraft: https://tar1090.adsbexchange.com/?icao=ad5d21
