### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by wiseman** [gbinal/dc-helicopters#39]
I've toyed with (written a couple drafts of) something similar for Los Angeles, so I am completely tickled that you've done it for real, so well.  Very inspiring!

<img width="606" alt="Screen Shot 2020-01-18 at 4 01 37 PM" src="https://user-images.githubusercontent.com/52466/72672249-e472c700-3a0b-11ea-8a3d-c67436156e36.png">

**Comment by gbinal** [comment]
Nice!  Keep an eye here and at another great project - http://twitter.com/helicoptersofdc.  more to come.
