### ISSUE TITLE
USCG helicopters - Chevy Chase MD

### ISSUE THREAD

**Issue by JH4811** [gbinal/dc-helicopters#40]
I live in Chevy Chase and see/hear helicopters a lot, flying low - when I get a visual they are often the USCG choppers. Not sure what is to be done since they have responsibility for defense of DC, but sometimes they are really low and I wonder if that's really necessary.

**Comment by gbinal** [comment]
:) I feel ya.  Regardless, I don't think they're going to change anytime soon.
