### ISSUE TITLE
Role of CBP S-76

### ISSUE THREAD

**Issue by ofcmcm87** [gbinal/dc-helicopters#41]
It’s the DHS Secretary’s transport. Also shared with the Commandant of the Coast Guard. In return, DHS secretary gets to ride in the Commandant’s Gulfstreams.

**Comment by gbinal** [comment]
That makes so much sense!  Thank you!

**Comment by NickSto** [comment]
@ofcmcm87 Do you have the registration number or ICAO hex code of the aircraft?

**Comment by gbinal** [comment]
Thanks again for this tip!  Updated the webpage.
