### ISSUE TITLE
Identify Air Force helicopters

### ISSUE THREAD

**Issue by NickSto** [gbinal/dc-helicopters#43]
Thanks to your site I've been able to identify the helicopters that fly by my place regularly as the [1st Helicopter Squadron](https://helicoptersofdc.com/helicopters/6-us-air-force-1st-helicopter-squadron/). And I've noticed that they never seem to appear on the [ADS-B Exchange](https://tar1090.adsbexchange.com/).

It'd be cool to find their FAA registry numbers for multiple reasons, like just knowing how many there are. It might also help me search for them on the ADS-B site. I'm curious if they're ever identified there, or if they fly without the regular transponders on.

**Comment by gbinal** [comment]
That's a great idea.  I'm making a note in another issue to see if we can ever suss it out.
