### ISSUE TITLE
More material to incorporate

### ISSUE THREAD

**Issue by gbinal** [gbinal/dc-helicopters#44]
General material to add:
* More videos
* Links to Google Images
* More photos to each details page
* Private photo [album](https://photos.google.com/share/AF1QipOHGz4WAcE-I63QyDTa3RCOZVV-MKb7y9hpNmbZSEF9FirN4InWMBXGCqBwX7m9GQ) of screenshots; [processed album](https://photos.google.com/album/AF1QipPiJnRWbGwNCAqZrWxVayGp111KY37VQP7PLyGw)

https://twitter.com/SkyCirclesDC/with_replies

**Comment by gbinal** [comment]
https://nextdoor.com/news_feed/?post=143026651&is=tpe&ct=NThIG0cJf0Wwn282--0eyzTV4Y2YpJsTIfS_SdFlBBttN937jQiDYoTghEK20l4n&ec=OWKiQRDj9vEHAYwTV6YMARldwuFdgGkeefhwfGYAE0s=&lc=16805

**Comment by gbinal** [comment]
https://en.m.wikipedia.org/wiki/1st_Helicopter_Squadron
https://www.jba.af.mil/News/Tag/73997/1st-helicopter-squadron/https://www.afdw.af.mil/News/Features/Display/Article/336361/andrews-helicopter-squadron-1st-only-of-its-kind/

**Comment by LoganSound** [comment]
Hope you don't mind me borrowing the name:
https://twitter.com/helicoptersofdc

**Comment by gbinal** [comment]
Not at all, @LoganSound !!!!

I was so stoked when I came across your account.  I've been meaning to follow up but in the meantime just wanted to say, 'Cool stuff!.'

**Comment by gbinal** [comment]
https://twitter.com/MikeIsler/status/1279538382956367873

**Comment by gbinal** [comment]
May 14, 2014 medevac from the mall

**Comment by gbinal** [comment]
Try to find footage of marine one taking off and joining formation, similar to this.

https://youtu.be/S8xylUa5vZM

**Comment by gbinal** [comment]
create a page, or maybe another microsite that is a mobile-friendly, quick swipe guide to the major culprits.

**Comment by gbinal** [comment]
Notes from rewatching State of Play: 

...

**Comment by gbinal** [comment]
Create a 'What are they doing' page

**Comment by gbinal** [comment]
ideas from Andrew's email...

**Comment by gbinal** [comment]
Link to live flightradar for DC - https://www.flightradar24.com/38.91,-77.05/12

**Comment by gbinal** [comment]
https://www.thedrive.com/the-war-zone/30152/this-is-our-best-look-yet-at-the-elite-fbi-hostage-rescue-teams-black-hawks

https://www.foxnews.com/us/low-flying-black-hawk-helicopter-descends-washington-d-c

https://www.thedrive.com/the-war-zone/33802/military-helicopters-descend-on-washington-in-bizarre-very-low-altitude-show-of-force



https://www.washingtonpost.com/national-security/2020/06/02/helicopter-protest-dc/

**Comment by gbinal** [comment]
https://twitter.com/policeoverhead
https://twitter.com/overheadbots
https://twitter.com/fedsoverhead

**Comment by gbinal** [comment]
https://www.thedrive.com/the-war-zone/33136/the-curious-case-of-customs-and-border-protections-mysterious-unmarked-s-76-helicopters

11-6-2020, noted as a DOJ helicopter instead of DHS

**Comment by gbinal** [comment]
A lot more here - https://github.com/gbinal/dc-helicopters/issues/1

**Comment by gbinal** [comment]
More about the CBP helicopter - https://github.com/gbinal/dc-helicopters/issues/2

**Comment by gbinal** [comment]
More from the Summer 2020 protests.  https://github.com/gbinal/dc-helicopters/issues/42

**Comment by gbinal** [comment]
Note the news helicopters that hover up 16th street to film the WH

**Comment by gbinal** [comment]
Track back to see if Trump's personal helicopter ever went over the district - N76DT

**Comment by gbinal** [comment]
https://globe.adsbexchange.com/

**Comment by gbinal** [comment]
Any way to figure out FAA registry numbers for the military aircraft in case they do squawk other times?

**Comment by gbinal** [comment]
Are the elevations prescribed so that different ones are at different elevations for safety?  ([note](https://aeronav.faa.gov/content/aeronav/heli_files/PDFs/Balt-Wash_Heli_14_P.pdf))

**Comment by gbinal** [comment]
The crazy incident during Carter's term - https://www.youtube.com/watch?v=tuphCzpzAmQ

**Comment by gbinal** [comment]
Images of usual flight paths

**Comment by gbinal** [comment]
Idea - the other helicopters are below a certain ceiling, so that hmx-1 had its own area

**Comment by gbinal** [comment]
Links on https://www.washingtonpost.com/local/helicopters-of-dc/2020/11/19/3e372c4c-28de-11eb-b847-66c66ace1afb_story.html

Also, search deeper.  Also newspapers.com

**Comment by gbinal** [comment]
this amazing video.  https://www.youtube.com/watch?v=zlUPEI2KsAE

Then, makes me think about trying to reach out to all squadrons to see who would be willing to do an interview or similar.

**Comment by gbinal** [comment]
https://www.cbsnews.com/news/us-coast-guard-blackjack-unit-intercepts-threats-in-washington-dc-airspace/

**Comment by gbinal** [comment]
video about marine one - 

other links I recently visited while clearing off phone?

**Comment by gbinal** [comment]
Add new USPP copter

**Comment by gbinal** [comment]
https://www.washingtonpost.com/national-security/2021/04/15/dc-guard-helicopter-george-floyd-protest/

**Comment by gbinal** [comment]
https://twitter.com/fergindc/status/1379476757477158913?s=20

**Comment by gbinal** [comment]
https://twitter.com/dcskycam

**Comment by gbinal** [comment]
https://mobile.twitter.com/districtheli

**Comment by gbinal** [comment]
2021 report from twitter.com/helicoptersofdc

**Comment by gbinal** [comment]
https://copterspotter2021.mystrikingly.com/

**Comment by gbinal** [comment]
Video from medevac at SCOTUS

https://twitter.com/RealTimeNews10/status/1517654930210832385?s=20&t=SXOkacWsHwlGVEGQpMIqQw

**Comment by gbinal** [comment]
https://hypothes.is/search?q=tag%3Ahelicoptersofdc

**Comment by gbinal** [comment]
re: NNSA - FAA registry number, flight path and photo of N412DE. Last seen flying a grid pattern at low altitude over Glover Park on November 2nd, 2020. https://imgur.com/a/NmbByR4

**Comment by gbinal** [comment]
Reason for much of the military airtime over Dc is just puppets getting in their hours/keeping the airframes in good condition (see GAO report).

**Comment by gbinal** [comment]
Plans are to replace the 1st squadron helicopters with these

https://en.wikipedia.org/wiki/AgustaWestland_AW139

**Comment by LoganSound** [comment]
notably change of type designation to AH139, I'm not sure replacement is as likely as supplement - the UH1N was rated the most reliable aircraft in the military by GAO. A pilot I spoke to in September said the latest hold up is they had to be recertified because of the modifications.

**Comment by gbinal** [comment]
https://www.washingtonpost.com/transportation/2023/04/25/helicopter-noise-complaints-dc/

**Comment by gbinal** [comment]
Note that NPP helicopter makes a particular point to check around the WH, Andrews, and in between before Presidential trips between the two...

**Comment by gbinal** [comment]
Consider a common elevations section - 

Air Force 1st sq. 500 feet over DC
250 over the river

nPP - 700 ft 

Marine one over dc 800 ft

**Comment by gbinal** [comment]
Note able to spot briefly on ads-b

**Comment by gbinal** [comment]
5-17 video of landing

**Comment by gbinal** [comment]
Movie content:

Jackal https://m.youtube.com/watch?v=CCz7aVHpDjo&t=150

**Comment by gbinal** [comment]
https://www.twz.com/air/coast-guard-will-get-a-new-mh-60-variant-to-replace-mh-65-helicopters

**Comment by gbinal** [comment]
https://www.reddit.com/r/washingtondc/comments/1qkvqog/rare_low_flight_over_washington_dc_n2qw_doing/
