### ISSUE TITLE
Helicopters Over Bethesda

### ISSUE THREAD

**Issue by cab4410** [gbinal/dc-helicopters#46]
We live in downtown Bethesda and have a 6-8 helicopters overhead nightly, they are not all going to Suburban Hospital.  Any chance you can show helicopter activity inside the Beltway, no just DC?

**Comment by NickSto** [comment]
FYI, if you're wondering what's overhead right now, most aircraft will show up on https://globe.adsbexchange.com/

**Comment by gbinal** [comment]
Totally reasonable request, @cab4410.  I'm probably going to keep focused on just DC proper to keep it manageable, but have added to the list of future sections to create to make a VA/MD page as well.  

+1 to the website or one of the mobile apps (I use flightradar24).
