### ISSUE TITLE
weird different helicopter ?

### ISSUE THREAD

**Issue by curiousinsilverspring** [gbinal/dc-helicopters#52]
so i've seen this thing a few times over the past year , always at night, only at night, never got a clear look at it during the day, hard to give a full description of it, but two things are clear - it sounds different, it's a lower pitch slower moving sound, and it has this weird round construction on the top or in front, hard to tell, but it looks like the main top rotor is enclosed, like the way drone props are, but just one in the center or front of it, it's like this big round weird very different thing ... has anybody seen this ?  i've reviewed as many listings, visual collections, as i could find and i have not seen this thing reported anywhere ... silver spring md ... last saw this on friday around 7pm, when it made 3 loops around our airspace

**Comment by gbinal** [comment]
I'm not sure but this was also recent and has a different sound.  Any thoughts?  

https://twitter.com/HelicoptersofDC/status/1343781346733412352

Did I look like this?  

https://en.wikipedia.org/wiki/MD_Helicopters_MD_500

**Comment by curiousinsilverspring** [comment]
Thanks for the message, but that wasn’t it.. there was definitely some weird round aspect to it around the main rotor, even in the dark it was clear it was very different...
