### ISSUE TITLE
Add 'yeti' helicopters

### ISSUE THREAD

**Issue by gbinal** [gbinal/dc-helicopters#59]
from the FBI, apparently.  

https://twitter.com/1crazyarchitect/status/1379195259700281344

**Comment by LoganSound** [comment]
if you create the FBI page I will fill out the info

**Comment by LoganSound** [comment]
"Federal Bureau of Investigation transports officials between its headquarters in Washington, D.C. and the FBI Academy in Quantico, Virginia utilizing its fleet of six Sikorsky UH-60M and three Bell 429 helicopters."
https://hyp.is/MzX6cBV0EeyGljM1JNSKGQ/www.gao.gov/assets/gao-21-200.pdf

**Comment by gbinal** [comment]
Closing in favor of #6
