### ISSUE TITLE
try flightaware to identify helicopters

### ISSUE THREAD

**Issue by gbinal** [gbinal/dc-helicopters#8]

**Comment by UndisclosedLocation** [comment]
I've personally had better luck tracking helicopters using flightradar24.  I find that often they won't even show up on flightaware.

**Comment by gbinal** [comment]
Great recommendation - thanks!

**Comment by gbinal** [comment]
Here's who I've been able to find on FlightRadar24 so far:  
* [x] Skybear
* [ ] Medstar
* [ ] MPD
* [ ] US Park Police
* [ ] Coast Guard
* [ ] US Army - _I believe they don't display_
* [ ] CBP
* [ ] US Air Force
* [ ] HMX-1 - _I believe they don't display_

**Comment by gbinal** [comment]
Add to related info page

**Comment by gbinal** [comment]
One that looks like MPD isn't on flight radar

**Comment by gbinal** [comment]
I've gone through this with all of the current main helicopters and am going to close this issue while still keeping an eye out for any others.

**Comment by gbinal** [comment]
@UndisclosedLocation - thanks again for the great recommendation

**Comment by wiseman** [comment]
For this I almost exclusively use https://adsbexchange.com/ in the Los Angeles area. I haven't checked its coverage over D.C.
